"""empty message

Revision ID: 8c0963d15558
Revises: 
Create Date: 2019-07-05 08:46:42.607989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c0963d15558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packagebookings', 'ConfirmedPaymentOn')
    op.add_column('payments', sa.Column('Extension', sa.String(length=10), nullable=True))
    op.add_column('payments', sa.Column('PaidOn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'PaidOn')
    op.drop_column('payments', 'Extension')
    op.add_column('packagebookings', sa.Column('ConfirmedPaymentOn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
